### ISSUE TITLE
Pre-Teaching checklist

### ISSUE THREAD

**Issue by pimotte** [impermeable/waterproof-vscode#90]
- [x] Merge subset/quantifier PR
- [x] Fix update text bug on slow machines (Ctrl+Z) (#98) 
- [x] Copy bug, related to updating dependencies (#106) 
- [x] Merge tab feature. (#109)
- [x] Insert/replace on diagnostics.
- [x] Make unchecked input areas blue again (@DikieDick)
- [x] Release coq-waterproof
- [x] Update versions (documention and checks) in vscode plugin
- [x] Release VS code plugin
- [x] Test whole installation
- [x] Publish that to marketplace & openvsx
- [x] Update the installer with version of waterproof
- [ ] Merge updated exercise branches
- [x] Create Gitpod environment(s)
- [x] Create devcontainer environment(s)
- [x] Update the Canvas page (links, description)
- (Final tests)
